languageCode = "es-ES"
title = "Littlebardo Chronicles"
baseurl = "/blog/"
theme = "hugo-theme-blueberry-detox"
publishDir = "../../public/blog"
[params]
    Author = "Littlebardo"
    dateformat = "02/01/2016"
    disqusShortname = "littlebardo"
    googleAnalytics = "UA-116134922-1"