languageCode = "es-ES"
title = "Littlebardo Chronicles"
baseurl = "https://littlebardo.com/blog/"
theme = "hucore"
publishDir = "../../public/blog"
[params]
    Author = "Littlebardo"
    Keywords = ""