language: node_js
node_js:
  - "7"
script:
  - echo "Deploy!!"
install:
  - travis_wait 30 npm install -g firebase-tools
after_success:
  - firebase deploy --project bardo-b9003 --token $FIREBASE_TOKEN